name: Maven Test

on:
  push:
    branches:
      - master  # Adjust this to your main branch name
    paths:
      - 'src/test/java/CalculusTest.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run TestNG Tests
      run: mvn -B test --file pom.xml
